application: 
  port: 8000
  host: "0.0.0.0"  # Important: use 0.0.0.0, not 127.0.0.1
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter" 

