database:
  host: "dpg-ct1hrhe8ii6s73ffvdbg-a.oregon-postgres.render.com"
  port: 5432
  username: "newsletter_gv1q_user"
  password: "ki3ie1JrszTi9LbQtJSnqX8Ig6VegLSo"
  database_name: "newsletter_gv1q"
  require_ssl: true

application:
  host: "0.0.0.0"
  port: 8000
  ssl:
  enabled: true
  cert_path: "/etc/ssl/certs/ca-certificates.crt"
  verify_peer: true

environment:
  SSL_CERT_DIR: "/etc/ssl/certs"
  SSL_CERT_FILE: "/etc/ssl/certs/ca-certificates.crt"
